/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cyh.vendingmachine;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;




/**
 *
 * @author esilv
 */
public class VMAdminPage extends javax.swing.JFrame {

    /**
     * Creates new form VMAdminPage
     */
    public VMAdminPage() {
        initComponents();
        loaditem();
        //create object VM to access class VendingMachine
        VendingMachine VM = new VendingMachine();
        //get value from private variable date
        VM.setDate();
        //set the value into date text field
        dateTF.setText(VM.getDate());
        cancelButton.setEnabled(false);
        saveButton.setEnabled(false);
        
        
    }
    public final void loaditem() {
        File file = new File("item.txt");
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String temp = br.readLine();
            String field = "";
            String [] col;
            
            temp = br.readLine();
            col = temp.trim().split(":");
            item1Button.setText(col[1]);
            
            
            temp = br.readLine();
            col = temp.trim().split(":");
            item2Button.setText(col[1]);

            temp = br.readLine();
            col = temp.trim().split(":");
            item3Button.setText(col[1]);

            temp = br.readLine();
            col = temp.trim().split(":");
            item4Button.setText(col[1]);

            temp = br.readLine();
            col = temp.trim().split(":");
            item5Button.setText(col[1]);

            temp = br.readLine();
            col = temp.trim().split(":");
            item6Button.setText(col[1]);

        }catch (FileNotFoundException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        } catch (IOException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        }
} 
    
    public void displayitem(){
        File file = new File("item.txt");
        try {
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String itemName = item1Button.getText();
                String [] col;
                Object [] allRec = br.lines().toArray();
                for (int i = 1; i < allRec.length; ++i){
                    col = allRec[i].toString().trim().split(":");
                    if (col[1].equalsIgnoreCase(itemName)){
                        itemNameTF.setText(col[1]);
                        itemPriceTF.setText(col[2]);
                        itemStockTF.setText(col[3]);
                    }
                    
                }
            }
            
        }catch (FileNotFoundException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        } catch (IOException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        item3Button = new javax.swing.JButton();
        item1Button = new javax.swing.JButton();
        item2Button = new javax.swing.JButton();
        item5Button = new javax.swing.JButton();
        item6Button = new javax.swing.JButton();
        item4Button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        itemStockTF = new javax.swing.JTextField();
        itemNameTF = new javax.swing.JTextField();
        itemPriceTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        itemNoTF = new javax.swing.JTextField();
        returnButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Product Customization Page");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        item3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item3ButtonActionPerformed(evt);
            }
        });

        item1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1ButtonActionPerformed(evt);
            }
        });

        item2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item2ButtonActionPerformed(evt);
            }
        });

        item5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item5ButtonActionPerformed(evt);
            }
        });

        item6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item6ButtonActionPerformed(evt);
            }
        });

        item4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item4ButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Item Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Item Price:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Item Stock:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Item Number:");

        itemNoTF.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemNameTF)
                    .addComponent(itemStockTF)
                    .addComponent(itemPriceTF)
                    .addComponent(itemNoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(itemNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(itemNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(itemPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(itemStockTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel Edit");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        dateTF.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(returnButton)
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addGap(50, 50, 50)
                                .addComponent(saveButton)
                                .addGap(60, 60, 60)
                                .addComponent(ExitButton)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(item1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(item2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(item3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(item4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(item5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(item6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnButton)
                    .addComponent(cancelButton)
                    .addComponent(saveButton)
                    .addComponent(ExitButton)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void item3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item3ButtonActionPerformed
        File file = new File("item.txt");
        try {
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String itemName = item3Button.getText();
                String [] col;
                Object [] allRec = br.lines().toArray();
                for (int i = 1; i < allRec.length; ++i){
                    col = allRec[i].toString().trim().split(":");
                    if (col[1].equalsIgnoreCase(itemName)){
                        itemNoTF.setText(col[0]);
                        itemNameTF.setText(col[1]);
                        itemPriceTF.setText(col[2]);
                        itemStockTF.setText(col[3]);
                    }
                    
                }
            }
            
        }catch (FileNotFoundException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        } catch (IOException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        }
        item1Button.setEnabled(false);
        item2Button.setEnabled(false);
        item3Button.setEnabled(false);
        item4Button.setEnabled(false);
        item5Button.setEnabled(false);
        item6Button.setEnabled(false);
        cancelButton.setEnabled(true);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_item3ButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        VendingMachine home = new VendingMachine();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void item1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1ButtonActionPerformed
        File file = new File("item.txt");
        try {
           try (BufferedReader br = new BufferedReader(new FileReader(file))) {
               String itemName = item1Button.getText();
               String [] col;
               Object [] allRec = br.lines().toArray();
               for (int i = 1; i < allRec.length; ++i){
                   col = allRec[i].toString().trim().split(":");
                   if (col[1].equalsIgnoreCase(itemName)){
                       itemNoTF.setText(col[0]);
                       itemNameTF.setText(col[1]);
                       itemPriceTF.setText(col[2]);
                       itemStockTF.setText(col[3]);
                   }
                   
               }
           }
            
        }catch (FileNotFoundException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        } catch (IOException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        }
       item1Button.setEnabled(false);
       item2Button.setEnabled(false);
       item3Button.setEnabled(false);
       item4Button.setEnabled(false);
       item5Button.setEnabled(false);
       item6Button.setEnabled(false);
       cancelButton.setEnabled(true);
       saveButton.setEnabled(true);
    }//GEN-LAST:event_item1ButtonActionPerformed

    private void item2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item2ButtonActionPerformed
        File file = new File("item.txt");
        try {
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String itemName = item2Button.getText();
                String [] col;
                Object [] allRec = br.lines().toArray();
                for (int i = 1; i < allRec.length; ++i){
                    col = allRec[i].toString().trim().split(":");
                    if (col[1].equalsIgnoreCase(itemName)){
                        itemNoTF.setText(col[0]);
                        itemNameTF.setText(col[1]);
                        itemPriceTF.setText(col[2]);
                        itemStockTF.setText(col[3]);
                    }
                    
                }
            }
            
        }catch (FileNotFoundException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        } catch (IOException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        }
        item1Button.setEnabled(false);
        item2Button.setEnabled(false);
        item3Button.setEnabled(false);
        item4Button.setEnabled(false);
        item5Button.setEnabled(false);
        item6Button.setEnabled(false);
        cancelButton.setEnabled(true);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_item2ButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        itemNoTF.setText(null);
        itemNameTF.setText(null);
        itemPriceTF.setText(null);
        itemStockTF.setText(null);
        item1Button.setEnabled(true);
        item2Button.setEnabled(true);
        item3Button.setEnabled(true);
        item4Button.setEnabled(true);
        item5Button.setEnabled(true);
        item6Button.setEnabled(true);
        cancelButton.setEnabled(false);
        saveButton.setEnabled(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        File file = new File("item.txt");
        try {
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String itemNo = itemNoTF.getText();
                String newItemName,newItemPrice,newItemStock;
                String [] col;
                Object [] allCol = br.lines().toArray();
                for (int i = 1; i < allCol.length; ++i){
                    col = allCol[i].toString().trim().split(":");
                    
                    if (col[0].equals(itemNo)){
                        newItemName = (itemNameTF.getText());
                        col[1] = newItemName;
                        newItemPrice = (itemPriceTF.getText());
                        col[2] = newItemPrice;
                        newItemStock = (itemStockTF.getText());
                        col[3] = newItemStock;
                        String newrec = "";
                        for (int x = 0; x < col.length; ++x) {
                            newrec = newrec + col[x] + ":";
                        }
                        allCol[i] = newrec;
                    }
                }  try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {
                    for (Object allCol1 : allCol) {
                        bw.write(allCol1 + "\n");
                    }
                }
            }
            JOptionPane.showMessageDialog(rootPane, "Record saved succesfully!");
            loaditem();

                                   
        }catch (FileNotFoundException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        } catch (IOException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        }
        itemNoTF.setText(null);
        itemNameTF.setText(null);
        itemPriceTF.setText(null);
        itemStockTF.setText(null);
        item1Button.setEnabled(true);
        item2Button.setEnabled(true);
        item3Button.setEnabled(true);
        item4Button.setEnabled(true);
        item5Button.setEnabled(true);
        item6Button.setEnabled(true);
        cancelButton.setEnabled(false);
        saveButton.setEnabled(false);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void item4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item4ButtonActionPerformed
        File file = new File("item.txt");
        try {
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String itemName = item4Button.getText();
                String [] col;
                Object [] allRec = br.lines().toArray();
                for (int i = 1; i < allRec.length; ++i){
                    col = allRec[i].toString().trim().split(":");
                    if (col[1].equalsIgnoreCase(itemName)){
                        itemNoTF.setText(col[0]);
                        itemNameTF.setText(col[1]);
                        itemPriceTF.setText(col[2]);
                        itemStockTF.setText(col[3]);
                    }
                    
                }
            }
            
        }catch (FileNotFoundException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        } catch (IOException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        }
        item1Button.setEnabled(false);
        item2Button.setEnabled(false);
        item3Button.setEnabled(false);
        item4Button.setEnabled(false);
        item5Button.setEnabled(false);
        item6Button.setEnabled(false);
        cancelButton.setEnabled(true);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_item4ButtonActionPerformed

    private void item5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item5ButtonActionPerformed
        File file = new File("item.txt");
        try {
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String itemName = item5Button.getText();
                String [] col;
                Object [] allRec = br.lines().toArray();
                for (int i = 1; i < allRec.length; ++i){
                    col = allRec[i].toString().trim().split(":");
                    if (col[1].equalsIgnoreCase(itemName)){
                        itemNoTF.setText(col[0]);
                        itemNameTF.setText(col[1]);
                        itemPriceTF.setText(col[2]);
                        itemStockTF.setText(col[3]);
                    }
                    
                }
            }
            
        }catch (FileNotFoundException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        } catch (IOException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        }
        item1Button.setEnabled(false);
        item2Button.setEnabled(false);
        item3Button.setEnabled(false);
        item4Button.setEnabled(false);
        item5Button.setEnabled(false);
        item6Button.setEnabled(false);
        cancelButton.setEnabled(true);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_item5ButtonActionPerformed

    private void item6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item6ButtonActionPerformed
        File file = new File("item.txt");
        try {
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String itemName = item6Button.getText();
                String [] col;
                Object [] allRec = br.lines().toArray();
                for (int i = 1; i < allRec.length; ++i){
                    col = allRec[i].toString().trim().split(":");
                    if (col[1].equalsIgnoreCase(itemName)){
                        itemNoTF.setText(col[0]);
                        itemNameTF.setText(col[1]);
                        itemPriceTF.setText(col[2]);
                        itemStockTF.setText(col[3]);
                    }
                    
                }
            }
            
        }catch (FileNotFoundException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        } catch (IOException e) {
            Logger.getLogger(VendingMachine.class.getName()).log(Level.SEVERE, null, e);
        }
        item1Button.setEnabled(false);
        item2Button.setEnabled(false);
        item3Button.setEnabled(false);
        item4Button.setEnabled(false);
        item5Button.setEnabled(false);
        item6Button.setEnabled(false);
        cancelButton.setEnabled(true);
        saveButton.setEnabled(true);
    }//GEN-LAST:event_item6ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VMAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VMAdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField dateTF;
    private javax.swing.JButton item1Button;
    private javax.swing.JButton item2Button;
    private javax.swing.JButton item3Button;
    private javax.swing.JButton item4Button;
    private javax.swing.JButton item5Button;
    private javax.swing.JButton item6Button;
    private javax.swing.JTextField itemNameTF;
    private javax.swing.JTextField itemNoTF;
    private javax.swing.JTextField itemPriceTF;
    private javax.swing.JTextField itemStockTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}

